### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by wtrocki** [apollographql/apollo-cache-persist#94]
The issue used to collect and stage all community ideas.

### Features

- [ ] Storage layout abstraction #132
- [x] Non async workflow #89 

### Bugs/Tech Debt

- [ ] MonoRepository #132 
- [ ] Content filtering
- [x] Improvements for storage interface
- [x] Package updates (Merging Renovate logs)
- [x] Upgrade config for rolup
- [x] Verifications for latest LocalForage, AsyncStorage etc. 
This will help with closing issues that may be outdated.
- [x] Bundling fixes #144 
- [x] Async API

### Docs

- [x] Document default and performant storage provider for the web 
- [x] Ionic support #47 

Feel free to suggest any changes that should land in the follow-up versions.
Looking for contributors and ideas to move this package forward.

**Comment by FezVrasta** [comment]
Is the async-ness of `persistCache` really needed? It's a bummer I have to re-arrange my whole application just to make the Apollo client asynchronous and show a the loading page/skeleton.

**Comment by wtrocki** [comment]
Most of the storage options like IndexedDB or AsyncStorage is asynchronous so that is why persistCache is async. The library allows users to pass their own storage that can be synchronous in theory. 
@FezVrasta Would it be possible to create a separate issue for a conversation about this matter. There is no need to rearrange the whole application as ApolloProvider will support async await syntax. From this and other issues It made it clear for me that we should provide examples for each framework on how to do things effectively.

**Comment by FezVrasta** [comment]
I'm not sure if https://github.com/apollographql/apollo-cache-persist/issues/89 tries to address my same concern or not.

I know how to implement an asyncronous apollo client on my React app, but that requires me to create a loading page while the apollo client is being prepared, and since I can't just `return 'Loading...'` I need to create a complex "skeleton like" loading page.

**Comment by wtrocki** [comment]
From my point of view, synchronous API can make things worse since users will literally get a white page till cache is inflated back or even worse - half backed UI till the cache can be loaded. Loading 1mb of cache using localStorage takes roughly 2s. On mobile this can go to 30 seconds. In real time scenarious application cache can go to even 10mb of data since we do not have garbage collection implemented (yet). 

I have been using this package extensively in many projects and also in open source library and truly understand what you mean, but from my point of view synchronous api, in this case, may make things even worse or impossible (as storage solutions that are providing great performance will be asynchronous)

**Comment by wtrocki** [comment]
Let's chat on the issue directly.

**Comment by lukadriel7** [comment]
Hello, thanks for the great work. I have a question.
I realized that wtrocki,  who seems to be the main person working on this package, is also working on https://github.com/aerogear/offix . That package lacks on the documentation side but I wanted to know if it is the one that should be considered over apollo-cache-persist since it seems to be more active. 

Thanks again

**Comment by wtrocki** [comment]
@lukadriel7 Thanks for letting us know. Offix is an offline extension for Apollo GraphQL and in no means is targeting to replace apollo-cache-persist. 

In fact, apollo-cache-persist is a critical element to achieve offline capabilities in offix and this is why I'm involved to make this package better and also contribute back to the amazing Apollo community. If you have any ideas for documentation improvements for Apollo-cache-persist please create a new issue. We are just starting to make improvements in cache persist and collect voice from the community so please stay tuned for updates.

Documentation for offix can be seen on our website: https://offix.dev

**Comment by lukadriel7** [comment]
@wtrocki that is great to know, I will be following this package more closely then. Thank you very much

**Comment by intellix** [comment]
Plans for TTL support?

**Comment by wtrocki** [comment]
@intellix This will be done in apollo cache directly. Persistence will need to just catch up with evicted items.

**Comment by hariDasu** [comment]
I am hesistant to migrate to apollo on react native for one reason, and that is because the cache is in-memory. I am maintaining a react native/redux/redux-sagas application and have been unable to successfully utilize redux/redux-persist as our persistent storage engine because even when setting the options to permit storage over 2MB and using `redux-persist-fs-storage` when the data loaded into memory gets larger the navigation between and within screens sees a noticeable slowdown.  as an alternative i've opted to use redux-persist to hold state management data (loading indicators etc) and some minimal data in memory to speed up client side interaction with data, but am now utilizing typeORM/SQLite as the persistent storage engine. my question is:

**are you considering adding SQLite as a storage engine either in conjunction with or as an alternative to the in memory cache for persistent storage?**

**Comment by wtrocki** [comment]
So there is this discussion happening in the community for more than year on how to move the cache from single key storage to actuall database. Imagine that all InMemory based storage gets saved as individual tables and keys. There is no problem to use SQLLite with CachePersist at the moment but what you can do is to simply have build wrapper that will **spread** apollo-cache into individual tables as you wish. 

This is something that I have been doing for production-based mobile apps on top of the apollo but it is really hard to get some consensus in community. Making this change inside this library is pretty easy problem is that it will break a lot of of clients and also it will make it incompabible with other cache solutions (like Hermes) that some people might not like. 
That is this change were not made despite many attemps (PR's to do so).

Simply replicating redux-persist storage and understanding of the apollo cache id composition (by default `Type:ID`) can do wonders inside app itself with little effort, but generic solution might not be the best. I think there are couple unmaintained forks for InMemoryCache that have persistence inside and there are couple wrappers that adapt SQL lite api into local storage API.
Problem for the moment that save will always save entire database - there is no way to know what was changed unless having direct access to the InMemoryCache implementation.

As for entire limitation - have you tried using IndexedDB on the web - depending on the browser your changes will end up in SQL lite anyway. Just not the app SQLLite database you can manage but actual webview SQLLite that is hidden behind IndexedDB API.

**Comment by hariDasu** [comment]
Our web client is not concerned with offline data access so we have neither considered nor implemented caching in the browser. For now typeORM/redux will work for us in react native but I will stay tuned for future updates on this matter thank you for the detailed response it was very informative

**Comment by vicary** [comment]
It would be great if this can support the `typeorm` since their `SQL.js` driver already has an option of `useLocalForage`.
